version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2778
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bot-network

  migrate:
    build: .
    depends_on:
      - db
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 2778
    networks:
      - bot-network
    command: ["python", "create_db.py"]

  bot:
    build: .
    depends_on:
      - migrate
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 2778
    networks:
      - bot-network

networks:
  bot-network:

volumes:
  pgdata:
